# Generated by Django 4.2.3 on 2023-08-03 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_brand_category_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
