# Generated by Django 4.2.3 on 2023-08-03 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0003_remove_product_brand_delete_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
