# Generated by Django 4.2.3 on 2023-08-04 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0005_brand_category_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=20, unique=True, verbose_name='Название группы')),
                ('about_group', models.TextField(blank=True, verbose_name='Информация о группе')),
                ('email', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ФИО учителя')),
                ('subject', models.CharField(max_length=50, verbose_name='Предмет')),
                ('email', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='ФИО судента')),
                ('age', models.IntegerField(blank=True, verbose_name='Возраст')),
                ('number', models.CharField(blank=True, max_length=11, verbose_name='Номер телефона')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='APP.group', verbose_name='Группа')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Курс')),
                ('price', models.IntegerField(default=100, verbose_name='цена')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.teacher', verbose_name='Учитель')),
            ],
        ),
    ]
