# Generated by Django 5.1.5 on 2025-01-25 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0006_group_teacher_student_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
